export const pricingTiers = [
  {
    title: "Free",
    monthlyPrice: 0,
    btnText: "Get started for free",
    popular: false,
    inverse: false,
    features: [
      "Unlimited projects",
      "Unlimited storage",
      "24/7 support",
      "Cancel anytime",
      "No credit card required",
      "Basic Support",
    ],
  },
  {
    title: "Pro",
    monthlyPrice: 9,
    btnText: "sign up now",
    popular: true,
    inverse: true,
    features: [
      "Unlimited projects",
      "Unlimited storage",
      "24/7 support",
      "Cancel anytime",
      "50gb of storage",
      "Unlimited users",
      "Priority Support",
    ],
  },
  {
    title: "Business",
    monthlyPrice: 29,
    btnText: "sign up now",
    popular: false,
    inverse: false,
    features: [
      "Unlimited projects",
      "Unlimited storage",
      "24/7 support",
      "Cancel anytime",
      "100gb of storage",
      "Unlimited users",
      "Advanced analytics",
      "Priority Support",
      "API access",
      "Advanced Security features",
    ],
  },
];
